use-kits: true

max-claim-corner-distance: 100
min-claim-width: 4

max-description-length: 80

dtr-regen: 36000

format-chat: true
formatted-chat: §8[{team}§8]§f{name}§8 » §7{message}
no-team-formatted-chat: §f{name}§8 » §7{message}

mob-spawn-in-claims: false

# Configurable Messages Below

msg-success: §6Success!
msg-must-be-in-faction: §cYou must be in a faction to do that!
msg-must-be-leader: §cYou must be the leader to do that!
msg-player-not-found: §cPlayer not found.
msg-no-invite: §cYou do not have any invitations!
